Volunteer Routes - Still work in progress
hack4impact-calpoly/city-farm-slo pull request #58
Opened 2022-02-08 01:43 UTC by vboo123

wanted to just push what I have, will finish it up in coming days

2022-02-15 02:56 UTC, vboo123 commented
Attempted to fix the volunteer routes. Let me know what needs to be changed

2022-02-15 04:02 UTC, vwinstea requested changes
Hi Vboo, thanks for working on this some more! Unfortunately, there's a couple of issues with this PR that will prevent the routes from working. I'll message you on Slack and see what we can do to get this task done this week. I know learning backend code can be tricky, so please lmk at any point in the process if you have any questions at all!

2022-02-15 04:02 UTC, vwinstea commented on backend/routes/volunteer.js
> +    res.send({req})
I'm unsure what you're doing here ... it looks like your just sending the request back. You should be querying the database using a [Mongoose query](https://mongoosejs.com/docs/queries.html). Lmk if you have any questions on how to implement it!

2022-02-15 04:02 UTC, vwinstea commented on backend/routes/volunteer.js
> +        eventID
The eventID isn't a property of the Volunteer, it's how we tie the event to the Volunteer. I'd read over the Issue description again and send me any questions you have.

2022-02-16 22:59 UTC, vboo123 commented
Final version here

2022-02-16 23:43 UTC, vwinstea approved these changes
Great work! FYI I updated the `volunteer/register` route so it accepts an eventID, so the data structure you need to pass in will look like this:
![image](https://user-images.githubusercontent.com/32073638/154376262-270f7111-d04c-4b40-99c6-c158fc97c35b.png)

2022-02-16 23:43 UTC, merged